app/models.py
from datetime import datetime
from time import time
from flask import current_app
from flask_login import UserMixin
from app import login


class User(UserMixin):

    def __init__(self,username):
        self.username=username

    def verify_ldap(self, password):
        if password == "yup":
            return True

    def get_id(self):
        return(self.username)

@login.user_loader
def load_user(username):
    return User(username)

app/main/forms.py
from flask import request
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import ValidationError, DataRequired, Length

from flask_wtf.file import FileField, FileRequired, FileAllowed

import re
import os

from app.models import User
from app import photos

class EditToolForm(FlaskForm):
    toolname=StringField("Tool Name", validators=[DataRequired()])
    category=SelectField(
        "Category",
        choices=[('Data', 'Data'), ("Metrics", "Metrics"), ("Modeling", "Modeling")],
        validators=[DataRequired()]
    )
    owner1=StringField("Owner 1", validators=[DataRequired()])
    owner2=StringField("Owner 2")
    owner3=StringField("Owner 3")
    about=StringField("About", validators=[DataRequired()])
    photo=FileField(validators=[FileAllowed(photos, 'Image only!')])
    submit=SubmitField("Apply Changes")



    @staticmethod
    def trim_toolname(toolname):
        trimmed_toolname=re.sub(r"([^A-Za-z0-9])+","-", toolname).lower()
        # re.findall(r"[A-Za-z0-9]+", "Data_!!Foundry")
        return(trimmed_toolname)


class DeleteToolButton(FlaskForm):
    delete=SubmitField("Delete Tool")

class DeleteToolForm(FlaskForm):
    toolname=StringField("Are you sure? Enter the tool name as it appears above:")
    submit=SubmitField("Delete")

app/__init__.py
import logging
from logging.handlers import RotatingFileHandler
import os
from flask import Flask, request, current_app
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_uploads import UploadSet, configure_uploads, IMAGES, patch_request_class
from config import Config


login = LoginManager()
login.login_view = 'auth.login'
login.login_message = ('Please log in to access this page.')
bootstrap = Bootstrap()
photos = UploadSet('photos', IMAGES)


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)


    configure_uploads(app, photos)
    patch_request_class(app)
    login.init_app(app)
    bootstrap.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    if not app.debug and not app.testing:
        if not os.path.exists('logs'):
            os.mkdir('logs')
        file_handler = RotatingFileHandler('logs/app.log',
                                           maxBytes=10240, backupCount=10)
        file_handler.setFormatter(logging.Formatter(
            '%(asctime)s %(levelname)s: %(message)s '
            '[in %(pathname)s:%(lineno)d]'))
        file_handler.setLevel(logging.INFO)
        app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('App startup')

    return app

from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from datetime import datetime
from flask import render_template, flash, redirect, url_for, request, \
    current_app, abort
from flask_login import current_user, login_required
import os
import yaml
import re
from app import photos
from app.models import User
from app.main import bp
from app.main.forms import EditToolForm, DeleteToolForm, DeleteToolButton

admins = ['cfede']

@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    yamls_to_read = get_file_names()
    yamls = load_yamls(yamls_to_read)

    if current_user.username not in admins:
        yamls = find_pages_owned(current_user.username, yamls)

    toolnames = [yaml['toolname-trim'] for yaml in yamls]

    return render_template('index.html',
                            toolnames=toolnames,
                            title=('Home'))


@bp.route("/tool/<toolname>", methods=['GET', 'POST'])
@login_required
def edit_tool(toolname):
    try:
        tool_yaml = load_yaml(toolname+".yml")
    except:
        tool_yaml = {}
        tool_yaml['owners']=[]

    form = EditToolForm()
    #delete_button =DeleteToolButton()


    if form.validate_on_submit():
        tool_yaml["toolname"] = form.toolname.data
        tool_yaml["toolname-trim"] = form.trim_toolname(form.toolname.data)
        tool_yaml["category"] = form.category.data
        tool_yaml["owners"] = [form.owner1.data, form.owner2.data, form.owner3.data]
        tool_yaml["about"] = form.about.data

        if form.photo.data:
            try:
                os.remove("page_data/screenshots/"+form.trim_toolname(form.toolname.data)+".jpg")
            except:
                pass
            photos.save(form.photo.data,
                        name=form.trim_toolname(form.toolname.data)+".jpg")
        else:
            if not os.path.exists("page_data/screenshots/"+form.trim_toolname(form.toolname.data)+".jpg"):
                flash("There isn't a screenshot on file. Please upload one.")
                return(redirect(url_for('main.edit_tool', toolname=toolname)))

        save_yaml(tool_yaml, tool_yaml['toolname-trim'])

        flash('Your changes have been saved')
        return(redirect(url_for('main.index')))
    elif request.method == "GET":
        try:
            form.toolname.data=tool_yaml["toolname"]
            form.category.data=tool_yaml["category"]
            form.owner1.data=tool_yaml["owners"][0]
            form.owner2.data=tool_yaml["owners"][1]
            form.owner3.data=tool_yaml["owners"][2]
            form.about.data=tool_yaml["about"]
        except KeyError:
            pass
    return render_template('edit_tool.html', title="Edit Tool",
                            toolname=toolname, form=form)
                            #delete_button=delete_button)

@bp.route("/tool/<toolname>/delete", methods=['GET', "POST"])
@login_required
def delete_tool(toolname):
    form = DeleteToolForm()
    try:
        tool_yaml = load_yaml(toolname+".yml")
        if form.validate_on_submit():
            if current_user.username in tool_yaml['owners'] or \
               current_user.username in admins:
                if toolname == form.toolname.data:
                    remove_yaml(toolname)
                    os.remove("page_data/screenshots/"+toolname+".jpg")
                    flash(toolname + ' has been deleted')
                    return(redirect(url_for('main.index')))
                else:
                    flash("The name you entered did not match")
            else:
                flash("You are not an admin or an owner")
    except:
        abort(404)
    return(render_template("delete_tool.html",
                            title="Delete Tool",
                            toolname = toolname,
                            form=form))


def get_file_names(page_dir="page_data"):
    file_names = os.listdir(page_dir)
    return [file_name for file_name in file_names \
            if re.match(r'.*\.yml', file_name)]

def load_yaml(file_name, page_dir="page_data"):
    file_name = page_dir + "/" + file_name
    with open(file_name) as f:
         return(yaml.load(f, Loader=yaml.FullLoader))

def load_yamls(file_names, page_dir="page_data"):
    return([load_yaml(file_name, page_dir) for file_name in file_names])

def save_yaml(a_dict, filename, page_dir="page_data"):
    with open(page_dir+"/"+filename+".yml", 'w') as file:
        yaml.dump(a_dict, file)

def remove_yaml(toolname, page_dir="page_data"):
    os.remove(page_dir+"/"+toolname+".yml")


def find_pages_owned(username, yamls):
    def match_username(username, yaml):
        if username in yaml['owners']:
            return yaml
    out = [match_username(username, yaml) for yaml in yamls]
    out = [yaml for yaml in out if yaml is not None]
    return out

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }}{% else %}{{ ('Welcome to the website') }}{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">{{ ('Home') }}</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_anonymous %}
                    <li><a href="{{ url_for('auth.login') }}">{{ ('Login') }}</a></li>
                    {% else %}
                    <li><a href="{{ url_for('auth.logout') }}">{{ ('Logout') }}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/delete_tool.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Delete Tool: {{ toolname }}</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>

{% endblock %}

app/templates/edit_tool.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Edit Tool</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    {% if toolname != "new_tool" %}
    <a href='{{ url_for( "main.delete_tool" , toolname=toolname ) }}'>Delete Tool</a>

    {% endif %}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Hi {{ current_user.username }}</h1>
    {% for toolname in toolnames %}
    <ul>
      <li> <a href="{{ url_for('main.edit_tool', toolname=toolname) }}">{{ toolname }} </a> </li>
    </ul>
    {% endfor %}
    <a href="{{ url_for('main.edit_tool', toolname='new_tool') }}">Create new tool</a>

{% endblock %}